name: cinemax
description: "Cinemax is a movie app that allows you to search for movies, see details, and watch trailers."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.7.0
  dartz: ^0.10.1
  go_router: ^14.6.3
  dio_cache_interceptor: ^3.5.1
  flutter_dotenv: ^5.2.1
  either_dart: ^1.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: BarlowSemiCondensed
      fonts:
        - asset: assets/fonts/BarlowSemiCondensed-Regular.ttf
        - asset: assets/fonts/BarlowSemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/BarlowSemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/BarlowSemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/BarlowSemiCondensed-Black.ttf
          weight: 900
